//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace WinLIRC.Configuration
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class irconfig
    {

        private string nameField;

        private string bitsField;

        private string flagsField;

        private string epsField;

        private string aepsField;

        private string headerField;

        private string threeField;

        private string twoField;

        private string oneField;

        private string zeroField;

        private string ptrailField;

        private string pleadField;

        private string footField;

        private string repeatField;

        private string pre_data_bitsField;

        private string pre_dataField;

        private string post_data_bitsField;

        private string post_dataField;

        private string preField;

        private string postField;

        private string gapField;

        private string repeat_gapField;

        private string min_repeatField;

        private string toggle_bitField;

        private string frequencyField;

        private string duty_cycleField;

        private string transmitterField;

        private code[] remote_codesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bits
        {
            get
            {
                return this.bitsField;
            }
            set
            {
                this.bitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string flags
        {
            get
            {
                return this.flagsField;
            }
            set
            {
                this.flagsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eps
        {
            get
            {
                return this.epsField;
            }
            set
            {
                this.epsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aeps
        {
            get
            {
                return this.aepsField;
            }
            set
            {
                this.aepsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string three
        {
            get
            {
                return this.threeField;
            }
            set
            {
                this.threeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string two
        {
            get
            {
                return this.twoField;
            }
            set
            {
                this.twoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string one
        {
            get
            {
                return this.oneField;
            }
            set
            {
                this.oneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zero
        {
            get
            {
                return this.zeroField;
            }
            set
            {
                this.zeroField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ptrail
        {
            get
            {
                return this.ptrailField;
            }
            set
            {
                this.ptrailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plead
        {
            get
            {
                return this.pleadField;
            }
            set
            {
                this.pleadField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string foot
        {
            get
            {
                return this.footField;
            }
            set
            {
                this.footField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string repeat
        {
            get
            {
                return this.repeatField;
            }
            set
            {
                this.repeatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pre_data_bits
        {
            get
            {
                return this.pre_data_bitsField;
            }
            set
            {
                this.pre_data_bitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pre_data
        {
            get
            {
                return this.pre_dataField;
            }
            set
            {
                this.pre_dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string post_data_bits
        {
            get
            {
                return this.post_data_bitsField;
            }
            set
            {
                this.post_data_bitsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string post_data
        {
            get
            {
                return this.post_dataField;
            }
            set
            {
                this.post_dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pre
        {
            get
            {
                return this.preField;
            }
            set
            {
                this.preField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string post
        {
            get
            {
                return this.postField;
            }
            set
            {
                this.postField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gap
        {
            get
            {
                return this.gapField;
            }
            set
            {
                this.gapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string repeat_gap
        {
            get
            {
                return this.repeat_gapField;
            }
            set
            {
                this.repeat_gapField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_repeat
        {
            get
            {
                return this.min_repeatField;
            }
            set
            {
                this.min_repeatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string toggle_bit
        {
            get
            {
                return this.toggle_bitField;
            }
            set
            {
                this.toggle_bitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string duty_cycle
        {
            get
            {
                return this.duty_cycleField;
            }
            set
            {
                this.duty_cycleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transmitter
        {
            get
            {
                return this.transmitterField;
            }
            set
            {
                this.transmitterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("codes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public code[] remote_codes
        {
            get
            {
                return this.remote_codesField;
            }
            set
            {
                this.remote_codesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class code
    {

        private string nameField;

        private string valueField;

        private codeKey keyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public codeKey key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum codeKey
    {

        /// <remarks/>
        NUMBER1,

        /// <remarks/>
        NUMBER2,

        /// <remarks/>
        NUMBER3,

        /// <remarks/>
        NUMBER4,

        /// <remarks/>
        NUMBER5,

        /// <remarks/>
        NUMBER6,

        /// <remarks/>
        NUMBER7,

        /// <remarks/>
        NUMBER8,

        /// <remarks/>
        NUMBER9,

        /// <remarks/>
        NUMBER0,

        /// <remarks/>
        ARROW_UP,

        /// <remarks/>
        ARROW_DOWN,

        /// <remarks/>
        ARROW_LEFT,

        /// <remarks/>
        ARROW_RIGHT,

        /// <remarks/>
        CHANNEL_UP,

        /// <remarks/>
        CHANNEL_DOWN,

        /// <remarks/>
        VOLUME_UP,

        /// <remarks/>
        VOLUME_DOWN,

        /// <remarks/>
        RECORD,

        /// <remarks/>
        PLAY,

        /// <remarks/>
        PAUSE,

        /// <remarks/>
        STOP,

        /// <remarks/>
        MENU,

        /// <remarks/>
        SELECT,

        /// <remarks/>
        CANCEL,

        /// <remarks/>
        MUTE,

        /// <remarks/>
        UNKNOWN,
    }
}